generic-pool:
  versions: ^2.0.0 || ^3.1.0
  commands: node test/instrumentation/modules/generic-pool.js
mysql:
  versions: ^2.0.0
  commands:
    - node test/instrumentation/modules/mysql/mysql.js
    - node test/instrumentation/modules/mysql/pool-release-1.js
redis:
  versions: ^2.0.0
  commands: node test/instrumentation/modules/redis.js
ioredis:
  versions: '>=2 <4'
  commands: node test/instrumentation/modules/ioredis.js
pg:
  versions: '>=4 <8'
  peerDependencies:
    - bluebird@^3.0.0
    - knex@^0.13.0
  commands:
    - node test/instrumentation/modules/pg/pg.js
    - node test/instrumentation/modules/pg/knex.js
bluebird:
  versions: '>=2 <4'
  commands:
    - node test/instrumentation/modules/bluebird/bluebird.js
    - node test/instrumentation/modules/bluebird/cancel.js
knex:
  versions: ^0.13.0 || ^0.12.5 || <0.12.4 >0.11.6 || <0.11.6 >0.9.0
  commands: node test/instrumentation/modules/pg/knex.js
ws:
  versions: '>=1 <4'
  commands: node test/instrumentation/modules/ws.js
graphql:
  node: '>=1.0.0'
  pretest: rm -fr node_modules/express-graphql
  versions: '>=0.7.0 <1.0.0'
  commands: node test/instrumentation/modules/graphql.js
express-graphql:
  node: '>=1.0.0'
  peerDependencies: graphql@0.8.2
  versions: ^0.6.1
  commands: node test/instrumentation/modules/express-graphql.js
koa-router:
  node: '>=6.0.0'
  peerDependencies: koa@2
  versions: '>=5.2.0 <8'
  commands: node test/instrumentation/modules/koa-router/index.js
